<?php

declare(strict_types=1);

namespace App\Tool\Symfony\Validator\Constraint;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints\CountryValidator;

final class CountryCodeValidator extends CountryValidator
{
    /**
     * @param CountryCode $constraint
     */
    public function validate($value, Constraint $constraint): void
    {
        if (!$constraint->caseSensitive) {
            $value = mb_strtoupper($value);
        }

        parent::validate($value, $constraint); // TODO: Change the autogenerated stub
    }
}
