parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Core/DependencyInjection/'
            - '../src/Core/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Core\Controller\:
        resource: '../src/Core/Controller/'
        tags: ['controller.service_arguments']

    App\Core\Service\Geocoder\GeocoderRegistry:
        arguments:
            $geocoders: !tagged 'app.geocoder'

    App\Core\Service\Geocoder\Google\GoogleMapsGeocoder:
        arguments:
            $apiKey: '%env(GOOGLE_GEOCODING_API_KEY)%'
        tags: ['app.geocoder']

    App\Core\Service\Geocoder\HereMaps\HereMapsGeocoder:
        arguments:
            $apiKey: '%env(HEREMAPS_GEOCODING_API_KEY)%'
        tags: ['app.geocoder']

    App\Core\CLI\InvalidateCoordinatesCacheCommand:
        arguments:
            $cacheMinutes: '%env(COORDINATES_CACHE_VALIDITY_IN_MINUTES)%'
