services:
    http_client.loggable:
        class: App\Tests\Doubles\Tool\Http\Client\BlockedTestHttpClient
        public: true

    App\Core\Repository\ResolvedAddressRepository:
        public: true
        arguments:
            $registry: '@Doctrine\Common\Persistence\ManagerRegistry'
